export const callLogs = [
    {
      id: '1',
      caller: '+1234567890',
      callee: '+1987654321',
      duration: '02:45',
      timestamp: '2025-04-10 10:00 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hello, how can I assist you today?',
        'Customer: मुझे अपने बिल के बारे में जानकारी चाहिए।',
        'Agent: Sure, let me pull that up for you.',
        'Customer: Thank you.',
      ],
    },
    {
      id: '2',
      caller: '+1234567890',
      callee: '+1987000000',
      duration: '03:20',
      timestamp: '2025-04-09 5:30 PM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Welcome to our support line.',
        'Customer: I want to cancel my subscription.',
        'Agent: I’m sorry to hear that. May I ask why?',
        'Customer: यह मेरी आवश्यकताओं को पूरा नहीं कर रहा है।',
      ],
    },
    {
      id: '3',
      caller: '+1234567890',
      callee: '+1987111222',
      duration: '04:12',
      timestamp: '2025-04-08 11:15 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hi, thanks for calling.',
        'Customer: इंटरनेट बहुत धीमा चल रहा है।',
        'Agent: Let me run a quick test on your connection.',
        'Customer: ठीक है, धन्यवाद।',
      ],
    },
    {
      id: '4',
      caller: '+1234567890',
      callee: '+1987666888',
      duration: '05:33',
      timestamp: '2025-04-08 3:00 PM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: How can I help you?',
        'Customer: My payment didn’t go through.',
        'Agent: Let me check your transaction details.',
        'Customer: Please do it fast.',
      ],
    },
    {
      id: '5',
      caller: '+1234567890',
      callee: '+1987333444',
      duration: '01:59',
      timestamp: '2025-04-07 9:45 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Good morning!',
        'Customer: Good morning. I need to change my plan.',
        'Agent: Alright, what plan are you currently on?',
        'Customer: Bronze.',
      ],
    },
    {
      id: '6',
      caller: '+1234567890',
      callee: '+1987555777',
      duration: '06:10',
      timestamp: '2025-04-07 4:20 PM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hello, how may I help you?',
        'Customer: मुझे नेटवर्क की समस्या आ रही है।',
        'Agent: क्या आप मुझे अपना स्थान बता सकते हैं?',
        'Customer: हाँ, दिल्ली में हूँ।',
      ],
    },
    {
      id: '7',
      caller: '+1234567890',
      callee: '+1987444888',
      duration: '03:47',
      timestamp: '2025-04-06 2:10 PM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Thank you for calling support.',
        'Customer: I need to update my contact information.',
        'Agent: I can help you with that.',
        'Customer: Great, thanks!',
      ],
    },
    {
      id: '8',
      caller: '+1234567890',
      callee: '+1987999222',
      duration: '02:30',
      timestamp: '2025-04-05 10:30 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hi, this is John from support.',
        'Customer: मेरा अकाउंट लॉक हो गया है।',
        'Agent: Let me unlock it for you right away.',
        'Customer: धन्यवाद!',
      ],
    },
    {
      id: '9',
      caller: '+1234567890',
      callee: '+1987666555',
      duration: '04:05',
      timestamp: '2025-04-04 1:00 PM',
      status: 'missed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Missed Call to +1987666555',
      ],
    },
    {
      id: '10',
      caller: '+1234567890',
      callee: '+1987333777',
      duration: '05:22',
      timestamp: '2025-04-03 6:45 PM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hello! How may I help you?',
        'Customer: मेरी स्पीड लिमिट बहुत जल्दी खत्म हो जाती है।',
        'Agent: I’ll suggest a better plan for your usage.',
        'Customer: That sounds good.',
      ],
    },
    {
      id: '11',
      caller: '+1234567890',
      callee: '+1987222333',
      duration: '03:55',
      timestamp: '2025-04-02 10:05 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Hello! We’ve detected some unusual activity.',
        'Customer: क्या मेरा डेटा सुरक्षित है?',
        'Agent: बिल्कुल, हमने एक्सेस ब्लॉक कर दिया है।',
        'Customer: धन्यवाद, मुझे राहत मिली।',
      ],
    },
    {
      id: '12',
      caller: '+1234567890',
      callee: '+1987111444',
      duration: '02:18',
      timestamp: '2025-04-01 11:30 AM',
      status: 'completed',
      recordingUrl: '/dummy-recording.mp3',
      transcription: [
        'Agent: Welcome! How can I assist?',
        'Customer: I want to know about your family plan.',
        'Agent: We have 3 options, let me explain them.',
        'Customer: Please do.',
      ],
    },
  ];
  